apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluator
  labels:
    app: evaluator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: evaluator
  template:
    metadata:
      labels:
        app: evaluator
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      terminationGracePeriodSeconds: 25
      containers:
      - name: evaluator-runner
        image: asia.gcr.io/natural-iridium-300411/craft-simulator
        workingDir: /workdir
        command: ["/bin/sh", "-c"]
        args:
          - |
            python3 -u pysrc/simulator.py evaluator --plays-per-write 10 --thread-num 4 --mcts-simulation-num 1500
        resources:
          requests:
            cpu: "4.5"
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
      volumes:
      - name: google-cloud-key
        secret:
          secretName: storage-key
